[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
  Content-Type = "application/xml"
  Cache-Control = "max-age=3600"
  Access-Control-Allow-Origin = "*"
